require("ui")
require("options")

vim.cmd.colorscheme("chroma")

require("autocmds")
require("keymaps")
require("diagnostics")
require("commands")
require("pack")
require("lsp")
require("netrw")
require("find")
require("grep")
require("statusline")
