# Monitor rule
monitorrule=name:HDMI-A-1,scale:1.33,rr:1,x:0,y:0
monitorrule=name:DP-1,x:813,y:0
monitorrule=name:HDMI-A-2,scale=1.33,x:3373,y:0

# Vertical monitor
tagrule=id:1,monitor_name:HDMI-A-1,no_hide:1,layout_name:vertical_scroller
tagrule=id:2,monitor_name:HDMI-A-1,no_hide:1,layout_name:vertical_scroller
tagrule=id:3,monitor_name:HDMI-A-1,no_hide:1,layout_name:vertical_scroller
tagrule=id:4,monitor_name:HDMI-A-1,no_hide:1,layout_name:vertical_scroller
tagrule=id:5,monitor_name:HDMI-A-1,no_hide:1,layout_name:vertical_scroller
tagrule=id:6,monitor_name:HDMI-A-1,no_hide:1,layout_name:vertical_scroller
tagrule=id:7,monitor_name:HDMI-A-1,no_hide:1,layout_name:vertical_scroller
tagrule=id:8,monitor_name:HDMI-A-1,no_hide:1,layout_name:vertical_scroller
tagrule=id:9,monitor_name:HDMI-A-1,no_hide:1,layout_name:vertical_scroller

# Main monitor
tagrule=id:1,monitor_name:DP-1,no_hide:1,layout_name:dwindle
tagrule=id:2,monitor_name:DP-1,no_hide:1,layout_name:monocle
