# layout support:
# tile,scroller,grid,deck,monocle,center_tile,vertical_tile,vertical_scroller
tagrule=id:*,layout_name:tile

windowrule=tags:2,appid:app.zen_browser.zen
windowrule=tags:4,appid:org.zennotes.ZenNotes
windowrule=tags:9,appid:org.telegram.desktop
