# -*- conf -*-

font=DejaVuSansM Nerd Font Mono, Noto Color Emoji:size=8
font-bold=DejaVuSansM Nerd Font Mono:style=Bold:size=8
font-italic=DejaVuSansM Nerd Font Mono:style=Oblique:size=8
font-bold-italic=DejaVuSansM Nerd Font Mono:style=Bold Oblique:size=8

pad=10x10

bold-text-in-bright=no
gamma-correct-blending=yes

initial-color-theme=dark

## Monochromatic UI
# base00 000000  base01 0a0a0a  base02 1e1e1e  base03 434343
# base04 858585  base05 b2b2b2  base06 cfcfcf  base07 ffffff
#
## Semantic
# base08 ca6789 red     base09 da8472 orange
# base0A eab532 yellow  base0B 6e9a5d green
# base0C 59aa90 cyan    base0D 088eaf blue
# base0E 6f5fc3 violet  base0F a47fc6 magenta

[colors-dark]
background=000000
foreground=b2b2b2
selection-background=1e1e1e
selection-foreground=ffffff

regular0=000000
regular1=ca6789 # red
regular2=6e9a5d # green
regular3=eab532 # yellow
regular4=088eaf # blue
regular5=6f5fc3 # violet
regular6=59aa90 # cyan
regular7=b2b2b2

bright0=434343
bright1=da8472 # orange
bright2=6e9a5d # green
bright3=eab532 # yellow
bright4=088eaf # blue
bright5=a47fc6 # magenta
bright6=59aa90 # cyan
bright7=ffffff

jump-labels=000000 eab532
scrollback-indicator=000000 088eaf
search-box-no-match=000000 ca6789
search-box-match=000000 eab532
urls=6f5fc3
flash=eab532

[colors-light]
background=ffffff
foreground=1e1e1e
selection-background=b2b2b2
selection-foreground=000000

regular0=000000
regular1=ca6789 # red
regular2=6e9a5d # green
regular3=eab532 # yellow
regular4=088eaf # blue
regular5=6f5fc3 # violet
regular6=59aa90 # cyan
regular7=858585

bright0=434343
bright1=da8472 # orange
bright2=6e9a5d # green
bright3=eab532 # yellow
bright4=088eaf # blue
bright5=a47fc6 # magenta
bright6=59aa90 # cyan
bright7=ffffff

jump-labels=000000 eab532
scrollback-indicator=000000 088eaf
search-box-no-match=000000 ca6789
search-box-match=000000 eab532
urls=6f5fc3
flash=088eaf
dim-blend-towards=white

[key-bindings]
color-theme-toggle=Control+Shift+t

# vim: ft=dosini
