# -*- conf -*-

font=DejaVuSansM Nerd Font Mono, Noto Color Emoji:size=8
font-bold=DejaVuSansM Nerd Font Mono:style=Bold:size=8
font-italic=DejaVuSansM Nerd Font Mono:style=Italic:size=8
font-bold-italic=DejaVuSansM Nerd Font Mono:style=Bold Italic:size=8

pad=10x10

# vim: ft=dosini
